#Perfil entorno de desarrollo

spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password:  ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto:
    show-sql:
    database-platform: