#Para desarrollo local ( localhost, root)

spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password:  ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

  sql:
    init:
      mode: never # cambiar a always
      schema-locations: classpath:schema.sql

  ecommerce:
    app:
      jwtSecret: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiYWRtaW4iOnRydWUsImlhdCI6MTUxNjIzOTAyMn0.KMUFsIDTnFmyG3nMiGM6H9FNFUROf3wh7SmqJp-QV30
      jwtExpirationMs: 86400000